baseURL: "https://blog.maulanamalik.my.id"
title: "Maulana malik jabbar budianto"
pagination:
  pagerSize: 5  # Ganti paginate: 5 → sudah deprecated

theme: PaperMod

googleAnalytics: G-E7YCFT5WXN
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableInlineShortcodes: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Maulana malik jabbar budianto
  description: "Nani Kore?"
  keywords: [Blog, Portfolio, Technology, SysAdmin]
  author: Me
  images: ["/images/opsculun.png"]  # Ganti jadi array, agar tidak error saat dirender
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  enableEmoji: true
  disableOpenGraph: false  # opsional, ganti ke true jika ingin menonaktifkan fitur OG (untuk mencegah error)
  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: "/static/images/favicon.ico"
    favicon16x16: "/static/images/favicon.ico"
    favicon32x32: "/static/images/favicon.ico"
    apple_touch_icon: "/static/images/favicon.ico"
    safari_pinned_tab: "/static/images/favicon.ico"

  label:
    text: "Home"
    icon: "/static/images/favicon.ico"
    iconHeight: 20

  profileMode:
    enabled: true
    title: "Maulana malik jabbar budianto"
    subtitle: "Opsculun"
    imageUrl: "/images/opsculun.png"
    imageTitle: "me"
    imageWidth: 200
    imageHeight: 200

  homeInfoParams:
    Title: "Maulana malik jabbar budianto"
    Content: "Opsculun"

  socialIcons:
    - name: email
      url: "mailto:maulanamalikjb147@gmail.com"
    - name: telegram
      url: "https://t.me/maulanamalikjb"
    - name: instagram
      url: "https://instagram.com/lana.maulanaaaa"
    - name: credly
      url: "https://www.credly.com/users/maulanamalik-jabbarbudianto"
    - name: Medium
      url: "https://medium.com/@maulanamalikjb147"
    - name: linkedin
      url: "https://www.linkedin.com/in/maulana-malik-jabbar-budianto-a15225234"

  editPost:
    URL: "https://github.com/maulanamalikjb147/opsculun/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "tags"]

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 10
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: Blogs
      name: Blogs
      url: /blogs/
      weight: 10
    - identifier: Search
      name: Search
      url: /search/
      weight: 10

pygmentsUseClasses: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: nordic
  goldmark:
    renderer:
      unsafe: true
